from Function import main  

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Une erreur innatendu est survenu : {e}")
